# Exploratory data analysis and risk profiling

In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries imported successfully")

Libraries imported successfully

## 2. Load Dataset

In [8]:
df = pd.read_csv("Delinquency_prediction_dataset.csv")

df.head(10)

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,CUST0001,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,CUST0002,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,CUST0003,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,CUST0004,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,CUST0005,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late
5,CUST0006,25,84042.0,700.0,0.650540,6,0,48361.0,0.260688,Unemployed,7,Gold,New York,On-time,Late,Missed,Missed,Missed,Late
6,CUST0007,38,35056.0,354.0,0.390581,3,0,4638.0,0.484265,employed,17,Platinum,New York,On-time,Missed,Missed,Late,Missed,Late
7,CUST0008,56,123215.0,415.0,0.532715,5,0,55776.0,0.358695,EMP,1,Student,New York,On-time,On-time,On-time,Late,Missed,Late
8,CUST0009,36,66991.0,405.0,0.413035,5,1,NaN,0.219854,Employed,12,Student,Phoenix,On-time,On-time,On-time,Missed,Late,On-time
9,CUST0010,40,34870.0,679.0,0.361824,4,0,93922.0,0.333081,EMP,5,Business,Los Angeles,On-time,Missed,Missed,On-time,Missed,Missed

## 3. Dataset Dimensions

In [16]:
# Number of rows and columns

rows, columns = df.shape

print("\n Number of customers:", rows)
print("\n Number of variables:", columns)

 Number of customers: 500

 Number of variables: 19

## 4. Dataset Information

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           500 non-null    object
 1   Age                   500 non-null    int64
 2   Income                461 non-null    float64
 3   Credit_Score          498 non-null    float64
 4   Credit_Utilization    500 non-null    float64
 5   Missed_Payments       500 non-null    int64
 6   Delinquent_Account    500 non-null    int64
 7   Loan_Balance          471 non-null    float64
 8   Debt_to_Income_Ratio  500 non-null    float64
 9   Employment_Status     500 non-null    object
 10  Account_Tenure        500 non-null    int64
 11  Credit_Card_Type      500 non-null    object
 12  Location              500 non-null    object
 13  Month_1               500 non-null    object
 14  Month_2               500 non-null    object
 15  Month_3               500 non-null    object
 16  Month_4               500 non-null    object
 17  Month_5               500 non-null    object
 18  Month_6               500 non-null    object
dtypes: float64(5), int64(4), object(10)
memory usage: 74.3+ KB

## 5. Statistical Summary

In [17]:
df.describe()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Account_Tenure
count,500.000000,461.000000,498.000000,500.000000,500.000000,500.000000,471.000000,500.000000,500.000000
mean,46.266000,108379.893709,577.716867,0.491446,2.968000,0.160000,48654.428875,0.298862,9.740000
std,16.187629,53662.723741,168.881211,0.197103,1.946935,0.366973,29395.537273,0.094521,5.923054
min,18.000000,15404.000000,301.000000,0.050000,0.000000,0.000000,612.000000,0.100000,0.000000
25%,33.000000,62295.000000,418.250000,0.356486,1.000000,0.000000,23716.500000,0.233639,5.000000
50%,46.500000,107658.000000,586.000000,0.485636,3.000000,0.000000,45776.000000,0.301634,10.000000
75%,59.250000,155734.000000,727.250000,0.634440,5.000000,0.000000,75546.500000,0.362737,15.000000
max,74.000000,199943.000000,847.000000,1.025843,6.000000,1.000000,99620.000000,0.552956,19.000000

## 6. Check Duplicate Records

In [19]:
duplicates = df.duplicated().sum()

print("\n Number of duplicate records:", duplicates)

 Number of duplicate records: 0

## 7. Missing Value Analysis

In [22]:
missing_values = df.isnull().sum()
missing_values

Customer_ID              0
Age                      0
Income                  39
Credit_Score             2
Credit_Utilization       0
Missed_Payments          0
Delinquent_Account       0
Loan_Balance            29
Debt_to_Income_Ratio     0
Employment_Status        0
Account_Tenure           0
Credit_Card_Type         0
Location                 0
Month_1                  0
Month_2                  0
Month_3                  0
Month_4                  0
Month_5                  0
Month_6                  0
dtype: int64

In [23]:
missing_percentage[missing_percentage > 0]

Income          7.8
Credit_Score    0.4
Loan_Balance    5.8
dtype: float64

## 8. Check Target Variable

In [26]:
df['Delinquent_Account'].value_counts()

Delinquent_Account
0    420
1     80
Name: count, dtype: int64

In [27]:
df['Delinquent_Account'].value_counts(normalize=True) * 100

Delinquent_Account
0    84.0
1    16.0
Name: proportion, dtype: float64

## 9. Correlation with delinquency

In [30]:
correlation = df.corr(numeric_only=True)

correlation['Delinquent_Account'].sort_values(ascending=False)

Delinquent_Account      1.000000
Income                  0.045409
Credit_Score            0.034833
Debt_to_Income_Ratio    0.034386
Credit_Utilization      0.034224
Age                     0.022508
Loan_Balance           -0.004320
Missed_Payments        -0.026478
Account_Tenure         -0.039829
Name: Delinquent_Account, dtype: float64

## 10. Missed payments vs delinquency

In [31]:
df.groupby('Delinquent_Account')['Missed_Payments'].mean()

Delinquent_Account
0    2.990476
1    2.850000
Name: Missed_Payments, dtype: float64

## 11. Credit utilization vs delinquency

In [33]:
df.groupby('Delinquent_Account')['Credit_Utilization'].mean()

Delinquent_Account
0    0.488505
1    0.506887
Name: Credit_Utilization, dtype: float64